# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Util-SelfDestruct
version:      1.20
version_from: lib/Util/SelfDestruct.pm
installdirs:  site
requires:
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
